version: '3.8'
services:
  database:
    image: postgres:15
    ports:
      - 5434:5432
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - prod
    restart: always
    
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './mewtonssl:/etc/nginx/ssl'
    depends_on:
      - backend
      - frontend
    networks:
      - prod
    restart: always

  frontend:
    build:
      context: ./frontend
    networks:
      - prod
    restart: always

  backend:
    build:
      context: ./backend
    depends_on:
      database:
        condition: service_started
    networks:
      - prod
    restart: always
    
networks:
  prod:
